
services:
  api:
      build:
        context: .
        dockerfile: Dockerfile 
      container_name: animu-alert
      restart: unless-stopped
      volumes:
        - ./config.json:/api/config.json



